# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import setup
import ptkhac
import cv2



class Ui_MainWindow(object):

    def open_Setup(self):
        self.Button_Setup = QtWidgets.QMainWindow()
        self.ui = setup.Ui_Setup_windows()
        self.ui.setupUi(self.Button_Setup)
        self.Button_Setup.show()


    def open_PTK(self):
        self.Buttton_SetPass = QtWidgets.QMainWindow()
        self.ui = ptkhac.Ui_PTK_windows()
        self.ui.setupUi(self.Buttton_SetPass)
        self.Buttton_SetPass.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_Setup = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.open_Setup())
        self.Button_Setup.setGeometry(QtCore.QRect(20, 130, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Button_Setup.setFont(font)
        self.Button_Setup.setObjectName("Button_Setup")
        self.Buttton_SetPass = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.open_PTK())
        self.Buttton_SetPass.setGeometry(QtCore.QRect(20, 30, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Buttton_SetPass.setFont(font)
        self.Buttton_SetPass.setObjectName("Buttton_SetPass")
        self.Button_exit = QtWidgets.QPushButton(self.centralwidget)
        self.Button_exit.setGeometry(QtCore.QRect(20, 230, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Button_exit.setFont(font)
        self.Button_exit.setObjectName("Button_exit")
        self.label_ghichoi = QtWidgets.QLabel(self.centralwidget)
        self.label_ghichoi.setGeometry(QtCore.QRect(270, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_ghichoi.setFont(font)
        self.label_ghichoi.setObjectName("label_ghichoi")
        self.Lb_Show_image = QtWidgets.QLabel(self.centralwidget)
        self.Lb_Show_image.setGeometry(QtCore.QRect(280, 80, 150, 150))
        self.Lb_Show_image.setText("")        
        self.Lb_Show_image.setPixmap(QtGui.QPixmap("D:/Project_KLTN/Lmtrp/001MBL_G4_S1_C.png"))
        self.Lb_Show_image.setObjectName("Lb_Show_image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    #-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0


    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_Setup.setText(_translate("MainWindow", "Cài Đặt"))
        self.Buttton_SetPass.setText(_translate("MainWindow", " Phương Thức Khác"))
        self.Button_exit.setText(_translate("MainWindow", "Thoát"))
        self.label_ghichoi.setText(_translate("MainWindow", "Nhận dạng Lòng bàn tay"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
