# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PTKhac.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PTK_windows(object):
    def setupUi(self, PTK_windows):
        PTK_windows.setObjectName("PTK_windows")
        PTK_windows.resize(480, 320)
        self.centralwidget = QtWidgets.QWidget(PTK_windows)
        self.centralwidget.setObjectName("centralwidget")
        self.Lb_TK = QtWidgets.QLabel(self.centralwidget)
        self.Lb_TK.setGeometry(QtCore.QRect(40, 20, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Lb_TK.setFont(font)
        self.Lb_TK.setObjectName("Lb_TK")
        self.Lb_MK = QtWidgets.QLabel(self.centralwidget)
        self.Lb_MK.setGeometry(QtCore.QRect(40, 120, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Lb_MK.setFont(font)
        self.Lb_MK.setObjectName("Lb_MK")
        self.text_TK = QtWidgets.QTextEdit(self.centralwidget)
        self.text_TK.setGeometry(QtCore.QRect(190, 30, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.text_TK.setFont(font)
        self.text_TK.setObjectName("text_TK")
        self.text_MK = QtWidgets.QTextEdit(self.centralwidget)
        self.text_MK.setGeometry(QtCore.QRect(190, 130, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.text_MK.setFont(font)
        self.text_MK.setObjectName("text_MK")
        self.Button_exit_PTK = QtWidgets.QPushButton(self.centralwidget)
        self.Button_exit_PTK.setGeometry(QtCore.QRect(40, 210, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Button_exit_PTK.setFont(font)
        self.Button_exit_PTK.setObjectName("Button_exit_PTK")
        PTK_windows.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PTK_windows)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        PTK_windows.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PTK_windows)
        self.statusbar.setObjectName("statusbar")
        PTK_windows.setStatusBar(self.statusbar)

        self.retranslateUi(PTK_windows)
        QtCore.QMetaObject.connectSlotsByName(PTK_windows)

    def retranslateUi(self, PTK_windows):
        _translate = QtCore.QCoreApplication.translate
        PTK_windows.setWindowTitle(_translate("PTK_windows", "MainWindow"))
        self.Lb_TK.setText(_translate("PTK_windows", "Tài Khoản"))
        self.Lb_MK.setText(_translate("PTK_windows", "Mật Khẩu"))
        self.Button_exit_PTK.setText(_translate("PTK_windows", "Thoát"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PTK_windows = QtWidgets.QMainWindow()
    ui = Ui_PTK_windows()
    ui.setupUi(PTK_windows)
    PTK_windows.show()
    sys.exit(app.exec_())
