# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Setup_windows(object):
    def setupUi(self, Setup_windows):
        Setup_windows.setObjectName("Setup_windows")
        Setup_windows.resize(480, 320)
        self.centralwidget = QtWidgets.QWidget(Setup_windows)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_maumoi = QtWidgets.QPushButton(self.centralwidget)
        self.Button_maumoi.setGeometry(QtCore.QRect(40, 250, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Button_maumoi.setFont(font)
        self.Button_maumoi.setObjectName("Button_maumoi")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 80, 150, 150))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:/Project_KLTN/Lmtrp/001MBL_G4_S1_C.png"))
        self.label.setObjectName("label")
        self.listView_daluu = QtWidgets.QListView(self.centralwidget)
        self.listView_daluu.setGeometry(QtCore.QRect(10, 50, 181, 191))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.listView_daluu.setFont(font)
        self.listView_daluu.setObjectName("listView_daluu")
        self.Lable_mauhientai = QtWidgets.QLabel(self.centralwidget)
        self.Lable_mauhientai.setGeometry(QtCore.QRect(40, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Lable_mauhientai.setFont(font)
        self.Lable_mauhientai.setObjectName("Lable_mauhientai")
        Setup_windows.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Setup_windows)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        Setup_windows.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Setup_windows)
        self.statusbar.setObjectName("statusbar")
        Setup_windows.setStatusBar(self.statusbar)

        self.retranslateUi(Setup_windows)
        QtCore.QMetaObject.connectSlotsByName(Setup_windows)

    def retranslateUi(self, Setup_windows):
        _translate = QtCore.QCoreApplication.translate
        Setup_windows.setWindowTitle(_translate("Setup_windows", "MainWindow"))
        self.Button_maumoi.setText(_translate("Setup_windows", "Mẫu mới"))
        self.Lable_mauhientai.setText(_translate("Setup_windows", "Mẫu hiện tại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Setup_windows = QtWidgets.QMainWindow()
    ui = Ui_Setup_windows()
    ui.setupUi(Setup_windows)
    Setup_windows.show()
    sys.exit(app.exec_())
